project_id = "ifjksvcktcglcydkrfyu"

[functions.check-missed-checkpoints]
verify_jwt = false

[functions.send-alert-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
